version: '3'
services:
  pgdb:
    container_name: dev-postgres-training-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cycle_service_db
      - POSTGRES_USER=cci
      - POSTGRES_PASSWORD=cci
    ports:
      - "5534:5432"
    expose:
      - '5411'
      # Where our data will be persisted
    #volumes:
      #- postgres-db-training:/var/lib/postgres
    networks:
      - postgres
# Names our volume
  pgadmin:
    container_name: postgres-pgadmin-db
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=ivo.costa@creativecapsule.com
      - PGADMIN_DEFAULT_PASSWORD=cci
    ports:
      - 8080:80
    networks:
      - postgres

volumes:
  postgres-db-training-cci:
networks:
  postgres: