const nodemailer = require('nodemailer');

const sendEmail = (mailBody) => {
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.userEmail,
      pass: process.env.userPassword,
    },
  });

  const mailOptions = mailBody;
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
    } else {
      console.log(`Email sent: ${info.response}`);
    }
  });
};

const sendWelcomeMail = (userDetails, newpassword) => {
  const mailBody = {
    from: process.env.EmailFrom,
    to: userDetails.email,
    subject: 'Successful Registration to Cycle Servicing',
    html: `
    <div style="width: 88%; height: 88%; margin: auto; text-align: left">
    <p style="font-size: larger; font-family: 'Franklin Gothic Medium'">
      <b> Dear ${userDetails.firstName} ${userDetails.lastName},</b>
    </p>
    <h3 style="font-family: 'Franklin Gothic Medium'; padding: 10px">
      Welcome to Cycle Servicing!
    </h3>
    <p
      style="
        font-size: large;
        font-family: 'Franklin Gothic Medium';
        padding: 10px;
      "
    >
      Thank you for registering for Cycle Servicing ! We provide best services
      at best prices. we all come to work every day to provide our customers
      with the best bicycle parts and accessories on the market. Our customers
      deserve the best and that influences everything we do. We are looking
      forward to provide you our best services.
    </p>
    <p
      style="
        font-family: 'Franklin Gothic Medium';
        font-size: larger;
        padding: 10px;
      "
    >
      Your Username is :<b> ${userDetails.instaUsername}</b><br />
      Your generated password is :<b> ${newpassword}</b>
    </p>
    <p
      style="
        padding: 10px;
        font-size: larger;
        font-family: 'Franklin Gothic Medium';
      "
    >
      Please Save this email for future reference. To continue with using our
      services please reset the password after login. If you have questions,
      please contact the support team.
      <br />This email is auto generated by software, do not reply back to
      this email.
      <br />
      <br />
      <b>Thank You,</b><br />
      Cycle Servicing Support
    </p>
  </div>`,
  };
  sendEmail(mailBody);
};

const sendUpdatedPasswordEmail = (userDetails, newpassword) => {
  const mailBody = {
    from: process.env.EmailFrom,
    to: userDetails.email,
    subject: 'Reset password for Cycle Servicing account',
    html: `
    <div style="width: 88%; height: 88%; margin: auto; text-align: left">
    <p style="font-size: larger; font-family: 'Franklin Gothic Medium'">
      <b> Hello ${userDetails.firstName} ${userDetails.lastName},</b>
    </p>
    <h3 style="font-family: 'Franklin Gothic Medium'; padding: 10px">
      Welcome to Cycle Servicing!
    </h3>
    <p
      style="
        font-size: large;
        font-family: 'Franklin Gothic Medium';
        padding: 10px;
      "
    >
      Your Password has been reset and the credentials for login are as
      follows :
    </p>
    <p
      style="
        font-family: 'Franklin Gothic Medium';
        font-size: larger;
        padding: 10px;
      "
    >
      Your Username is :<b> ${userDetails.instaUsername}</b><br />
      Your generated password is :<b> ${newpassword}</b>
    </p>
    <p
      style="
        padding: 10px;
        font-size: larger;
        font-family: 'Franklin Gothic Medium';
      "
    >
      Please Save this email for future reference.To continue with using our
      services please reset the password after login. If you have questions,
      please contact the support team.
      <br />This email is auto generated by software, do not reply back to
      this email.
      <br />
      <br />
      <b>Best Regards,</b><br />
      Cycle Servicing Team
    </p>
  </div> `,
  };
  sendEmail(mailBody);
};

const sendSurveyThroughEmail = (userDetails, surveyLink) => {
  const mailBody = {
    from: process.env.EmailFrom,
    to: userDetails.email,
    subject: 'How can we make Cycle Servicing work for you?',
    html: `
    <div style="width: 88%; height: 88%; margin: auto; text-align: left">
    <p style="font-size: larger; font-family: 'Franklin Gothic Medium'">
      <b> Dear ${userDetails.firstName} ${userDetails.lastName},</b>
    </p>
    <h3 style="font-family: 'Franklin Gothic Medium'; padding: 10px">
      We want your feedback about everything!
    </h3>
    <p
      style="
        font-size: large;
        font-family: 'Franklin Gothic Medium';
        padding: 10px;
      "
    >
      We're always working to improve User experience on Cycle Servicing
      platforms for better and faster booking of cycle servicing online. Your
      feedbacks helps us to decide which features to build ,and what
      improvements to be made to our platform.
    </p>
    <p
      style="
        font-family: 'Franklin Gothic Medium';
        font-size: larger;
        padding: 10px;
      "
    >
      To Help Us make Cycle Servicing Centre the best it can be, we want your
      feedback today. Take a few minutes to fill out our survey by clicking
      the button below.
    </p>
    <center><input style="
    align-items: center;
    background-color: goldenrod;
    padding: 10px;
    font-size: larger;
    font-family: 'Franklin Gothic Medium';" type="button" onclick="location.href='${surveyLink}'" value="Start the Survey" />
    </center>
      <p
        style="
          padding: 10px;
          font-size: larger;
          font-family: 'Franklin Gothic Medium';
        "
      >
      <br />
      Thanks for your Time.
      <br />
      </br>
      <b>Best Regards,</b><br />
      Cycle Servicing Team
    </p>
  </div> `,
  };
  sendEmail(mailBody);
};

module.exports = {
  sendWelcomeMail,
  sendUpdatedPasswordEmail,
  sendSurveyThroughEmail,
};
